services:
  iut_commandes:
    container_name: iut_commandes
    image: node:lts
    env_file: ./service/.env
    working_dir: /usr/src/app
    volumes:
      - ./service/api:/usr/src/app
    ports:
      - 3333:3000
    command: npm start
    depends_on:
      - iut_db
    links:
      - iut_db
    networks:
      - iut
  
  iut_suivi:
    container_name: iut_suivi
    image: node:lts
    env_file: ./service/.env
    working_dir: /usr/src/app
    volumes:
      - ./service/suivi:/usr/src/app
    ports:
      - 3332:3000
    command: npm start
    depends_on:
      - iut_db
    links:
      - iut_db
    networks:
      - iut
  
  iut_auth:
    container_name: iut_auth
    image: node:lts
    env_file: ./service/.env
    working_dir: /usr/src/app
    volumes:
      - ./service/auth:/usr/src/app
    ports:
      - 3331:3000
    command: npm start
    depends_on:
      - iut_db
    links:
      - iut_db
    networks:
      - iut
  
  iut_gatewayBack:
    container_name: gatewayBack
    image: node:lts
    env_file: ./service/.env
    working_dir: /usr/src/app
    volumes:
      - ./service/gatewayBack:/usr/src/app
    ports:
      - 3334:3000
    command: npm start
    networks:
      - iut

  iut_adminer:
    container_name: iut_adminer
    image: adminer
    ports: 
      - 8080:8080
    depends_on:
      - iut_db
    networks: 
      - iut

  iut_db:
    container_name: iut_db
    image: mariadb:latest
    env_file: ./service/.env
    volumes:
      - ./service/db:/var/lib/mysql
      - ./service/schema.sql:/docker-entrypoint-initdb.d/1.sql
      - ./service/data.sql:/docker-entrypoint-initdb.d/2.sql
    networks:
      - iut

networks:
  iut:
    driver: bridge
  